#!/usr/bin/env python3
"""Regenerate the generated parts of README.md from repository sources.

Two things in README.md are derived, not hand-written:

1. The plugin table between the ``<!-- plugins:start -->`` and
   ``<!-- plugins:end -->`` markers — built from ``bundles.yaml`` group
   ids, display names, descriptions, and skill lists.
2. Release-tag pins in install examples (``lgtm-hq/ai-skills@vX.Y.Z``,
   ``@lgtm-hq/ai-skills@X.Y.Z``, ``gh release download vX.Y.Z``) and the
   prose npm↔tag pair (`` `@X.Y.Z` ↔ `vX.Y.Z` ``) — synced to the
   ``version`` in ``pyproject.toml``.

Usage:
    uv run python scripts/generate_readme.py          # rewrite README.md
    uv run python scripts/generate_readme.py --check  # fail if stale
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

from generate_marketplace import BundlesDocument, load_validated_bundles

PLUGINS_START = "<!-- plugins:start -->"
PLUGINS_END = "<!-- plugins:end -->"

_GENERATED_NOTE = (
    "<!-- Generated by scripts/generate_readme.py from bundles.yaml; "
    "do not edit by hand. -->"
)

_UNGROUPED_NOTE = (
    "Skills listed under `ungrouped` in `bundles.yaml` are not marketplace plugins."
)

_VERSION_PIN_PATTERNS = (
    re.compile(r"(lgtm-hq/ai-skills@v)\d+\.\d+\.\d+"),
    re.compile(r"(@lgtm-hq/ai-skills@)\d+\.\d+\.\d+"),
    re.compile(r"(gh release download v)\d+\.\d+\.\d+"),
)

# Prose pair on the install intro line; both sides must move together.
_PROSE_VERSION_PAIR_PATTERN = re.compile(
    r"`@\d+\.\d+\.\d+` ↔ `v\d+\.\d+\.\d+`",
)


def _repo_root() -> Path:
    """Return the repository root (parent of ``scripts/``).

    Returns:
        Absolute path to the ai-skills repository root.
    """
    return Path(__file__).resolve().parents[1]


def _pipe_cell(text: str) -> str:
    """Collapse whitespace and escape pipes for a Markdown table cell.

    YAML folded or literal scalars can embed newlines; a raw newline would
    split the generated table row.

    Args:
        text: Raw cell text.

    Returns:
        Single-line text with ``|`` escaped.
    """
    return " ".join(text.split()).replace("|", "\\|")


def _render_plugin_table(*, bundles: BundlesDocument) -> str:
    """Render first-party plugins as a Markdown table.

    Ungrouped skills are not marketplace plugins, so they are omitted from
    the table and mentioned in a following note when present.

    Args:
        bundles: Parsed and validated bundle document.

    Returns:
        Markdown table (no trailing newline).
    """
    lines = [
        "| Plugin | Id | Description | Skills |",
        "| --- | --- | --- | --- |",
    ]
    for group in bundles.groups.values():
        skill_links = ", ".join(
            f"[{skill_id}](skills/{skill_id}/SKILL.md)" for skill_id in group.skills
        )
        lines.append(
            "| "
            f"{_pipe_cell(group.name)} | "
            f"`{group.plugin_id}` | "
            f"{_pipe_cell(group.description)} | "
            f"{skill_links} |",
        )
    if bundles.ungrouped:
        lines.extend(["", _UNGROUPED_NOTE])
    return "\n".join(lines)


def _render_plugins_section(*, bundles: BundlesDocument) -> str:
    """Render the full generated plugins section, markers included.

    Args:
        bundles: Parsed and validated bundle document.

    Returns:
        Markdown from ``<!-- plugins:start -->`` through
        ``<!-- plugins:end -->``.
    """
    table = _render_plugin_table(bundles=bundles)
    return (
        f"{PLUGINS_START}\n"
        "<!-- markdownlint-disable MD013 -->\n"
        f"{_GENERATED_NOTE}\n\n"
        f"{table}\n\n"
        f"<!-- markdownlint-enable MD013 -->\n{PLUGINS_END}"
    )


def _current_version(*, repo_root: Path) -> str:
    """Read the project version from ``pyproject.toml``.

    Args:
        repo_root: Repository root path.

    Returns:
        The ``project.version`` string, e.g. ``0.1.22``.

    Raises:
        ValueError: If the version key is missing.
    """
    data = tomllib.loads((repo_root / "pyproject.toml").read_text(encoding="utf-8"))
    version = data.get("project", {}).get("version")
    if not isinstance(version, str) or not version:
        msg = "pyproject.toml is missing project.version"
        raise ValueError(msg)
    return version


def _sync_version_pins(*, text: str, version: str) -> str:
    """Rewrite release-tag pins in README text to the given version.

    Args:
        text: README markdown.
        version: Target semver string (without the ``v`` prefix).

    Returns:
        README text with all recognized pins updated.
    """
    for pattern in _VERSION_PIN_PATTERNS:
        text = pattern.sub(rf"\g<1>{version}", text)
    return _PROSE_VERSION_PAIR_PATTERN.sub(
        f"`@{version}` ↔ `v{version}`",
        text,
    )


def render_readme(*, repo_root: Path) -> str:
    """Return README.md content with generated parts brought up to date.

    Args:
        repo_root: Repository root path.

    Returns:
        Full README markdown with a fresh plugin table and version pins.

    Raises:
        ValueError: If the plugin markers are missing or out of order.
    """
    readme_path = repo_root / "README.md"
    text = readme_path.read_text(encoding="utf-8")
    start = text.find(PLUGINS_START)
    end = text.find(PLUGINS_END)
    if start == -1 or end == -1 or end < start:
        msg = f"README.md must contain {PLUGINS_START} before {PLUGINS_END}"
        raise ValueError(msg)
    bundles = load_validated_bundles(repo_root=repo_root)
    section = _render_plugins_section(bundles=bundles)
    text = text[:start] + section + text[end + len(PLUGINS_END) :]
    return _sync_version_pins(
        text=text,
        version=_current_version(repo_root=repo_root),
    )


def main() -> None:
    """CLI entry: write or check the generated parts of README.md."""
    parser = argparse.ArgumentParser(
        description=(
            "Regenerate the README plugin table from bundles.yaml and "
            "sync release-tag pins to pyproject.toml"
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if README.md is out of date",
    )
    args = parser.parse_args()

    repo_root = _repo_root()
    readme_path = repo_root / "README.md"
    rendered = render_readme(repo_root=repo_root)

    if args.check:
        if readme_path.read_text(encoding="utf-8") != rendered:
            print(
                "README.md is out of date; "
                "run uv run python scripts/generate_readme.py",
                file=sys.stderr,
            )
            sys.exit(1)
        return

    readme_path.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
