#!/usr/bin/env python3
"""Regenerate the generated parts of README.md from repository sources.

Two things in README.md are derived, not hand-written:

1. The ``## Skills`` section between the ``<!-- skills:start -->`` and
   ``<!-- skills:end -->`` markers — built from ``bundles.yaml`` group
   names/descriptions and each skill's ``SKILL.md`` frontmatter, with
   every skill hyperlinked to its ``SKILL.md``.
2. Release-tag pins in install examples (``lgtm-hq/ai-skills@vX.Y.Z``,
   ``@lgtm-hq/ai-skills@X.Y.Z``, ``gh release download vX.Y.Z``) and the
   prose npm↔tag pair (`` `@X.Y.Z` ↔ `vX.Y.Z` ``) — synced to the
   ``version`` in ``pyproject.toml``.

Usage:
    uv run python scripts/generate_readme.py          # rewrite README.md
    uv run python scripts/generate_readme.py --check  # fail if stale
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

import yaml

from generate_marketplace import BundlesDocument, load_validated_bundles
from skill_frontmatter import split_frontmatter

SKILLS_START = "<!-- skills:start -->"
SKILLS_END = "<!-- skills:end -->"

_GENERATED_NOTE = (
    "<!-- Generated by scripts/generate_readme.py from bundles.yaml and "
    "SKILL.md frontmatter; do not edit by hand. -->"
)

_UNGROUPED_HEADING = "Other"
_UNGROUPED_DESCRIPTION = (
    'Project-specific and optional skills (the installer\'s "Other" bucket).'
)

_VERSION_PIN_PATTERNS = (
    re.compile(r"(lgtm-hq/ai-skills@v)\d+\.\d+\.\d+"),
    re.compile(r"(@lgtm-hq/ai-skills@)\d+\.\d+\.\d+"),
    re.compile(r"(gh release download v)\d+\.\d+\.\d+"),
)

# Prose pair on the install intro line; both sides must move together.
_PROSE_VERSION_PAIR_PATTERN = re.compile(
    r"`@\d+\.\d+\.\d+` ↔ `v\d+\.\d+\.\d+`",
)


def _repo_root() -> Path:
    """Return the repository root (parent of ``scripts/``).

    Returns:
        Absolute path to the ai-skills repository root.
    """
    return Path(__file__).resolve().parents[1]


def _read_skill_description(*, skill_md: Path) -> str:
    """Load the ``description`` value from a skill's frontmatter.

    Args:
        skill_md: Path to ``SKILL.md`` under ``skills/<id>/``.

    Returns:
        The description text with folded newlines collapsed to spaces.

    Raises:
        ValueError: If frontmatter or the description key is missing.
    """
    frontmatter, _ = split_frontmatter(skill_md.read_text(encoding="utf-8"))
    if frontmatter is None:
        msg = f"Missing frontmatter in {skill_md}"
        raise ValueError(msg)
    data = yaml.safe_load(frontmatter)
    if not isinstance(data, dict) or not isinstance(data.get("description"), str):
        msg = f"Missing string description in {skill_md}"
        raise ValueError(msg)
    return " ".join(data["description"].split())


def _first_sentence(text: str) -> str:
    """Return the first sentence of a description.

    Splits on the first period followed by whitespace and an uppercase
    letter, so abbreviations like ``e.g.`` do not truncate early.

    Args:
        text: Full description text.

    Returns:
        The first sentence, ending with its period.
    """
    return re.split(r"(?<=\.)\s+(?=[A-Z])", text, maxsplit=1)[0]


def _render_group(
    *,
    heading: str,
    description: str,
    skills: tuple[str, ...],
    repo_root: Path,
) -> str:
    """Render one bundle group as a heading plus hyperlinked skill bullets.

    Args:
        heading: Group display name.
        description: One-line group description.
        skills: Skill ids in the group, in ``bundles.yaml`` order.
        repo_root: Repository root path.

    Returns:
        Markdown block for the group (no trailing newline).
    """
    lines = [f"### {heading}", ""]
    if description:
        lines.extend([description, ""])
    for skill_id in skills:
        skill_md = repo_root / "skills" / skill_id / "SKILL.md"
        summary = _first_sentence(_read_skill_description(skill_md=skill_md))
        lines.append(f"- **[{skill_id}](skills/{skill_id}/SKILL.md)** — {summary}")
    return "\n".join(lines)


def _render_skills_section(*, repo_root: Path, bundles: BundlesDocument) -> str:
    """Render the full generated skills section, markers included.

    Args:
        repo_root: Repository root path.
        bundles: Parsed and validated bundle document.

    Returns:
        Markdown from ``<!-- skills:start -->`` through ``<!-- skills:end -->``.
    """
    blocks = [
        _render_group(
            heading=group.name,
            description=group.description,
            skills=group.skills,
            repo_root=repo_root,
        )
        for group in bundles.groups.values()
    ]
    if bundles.ungrouped:
        blocks.append(
            _render_group(
                heading=_UNGROUPED_HEADING,
                description=_UNGROUPED_DESCRIPTION,
                skills=tuple(sorted(bundles.ungrouped)),
                repo_root=repo_root,
            ),
        )
    body = "\n\n".join(blocks)
    return (
        f"{SKILLS_START}\n"
        "<!-- markdownlint-disable MD013 -->\n"
        f"{_GENERATED_NOTE}\n\n"
        f"{body}\n\n"
        f"<!-- markdownlint-enable MD013 -->\n{SKILLS_END}"
    )


def _current_version(*, repo_root: Path) -> str:
    """Read the project version from ``pyproject.toml``.

    Args:
        repo_root: Repository root path.

    Returns:
        The ``project.version`` string, e.g. ``0.1.22``.

    Raises:
        ValueError: If the version key is missing.
    """
    data = tomllib.loads((repo_root / "pyproject.toml").read_text(encoding="utf-8"))
    version = data.get("project", {}).get("version")
    if not isinstance(version, str) or not version:
        msg = "pyproject.toml is missing project.version"
        raise ValueError(msg)
    return version


def _sync_version_pins(*, text: str, version: str) -> str:
    """Rewrite release-tag pins in README text to the given version.

    Args:
        text: README markdown.
        version: Target semver string (without the ``v`` prefix).

    Returns:
        README text with all recognized pins updated.
    """
    for pattern in _VERSION_PIN_PATTERNS:
        text = pattern.sub(rf"\g<1>{version}", text)
    return _PROSE_VERSION_PAIR_PATTERN.sub(
        f"`@{version}` ↔ `v{version}`",
        text,
    )


def render_readme(*, repo_root: Path) -> str:
    """Return README.md content with generated parts brought up to date.

    Args:
        repo_root: Repository root path.

    Returns:
        Full README markdown with a fresh skills section and version pins.

    Raises:
        ValueError: If the skills markers are missing or out of order.
    """
    readme_path = repo_root / "README.md"
    text = readme_path.read_text(encoding="utf-8")
    start = text.find(SKILLS_START)
    end = text.find(SKILLS_END)
    if start == -1 or end == -1 or end < start:
        msg = f"README.md must contain {SKILLS_START} before {SKILLS_END}"
        raise ValueError(msg)
    bundles = load_validated_bundles(repo_root=repo_root)
    section = _render_skills_section(repo_root=repo_root, bundles=bundles)
    text = text[:start] + section + text[end + len(SKILLS_END) :]
    return _sync_version_pins(
        text=text,
        version=_current_version(repo_root=repo_root),
    )


def main() -> None:
    """CLI entry: write or check the generated parts of README.md."""
    parser = argparse.ArgumentParser(
        description=(
            "Regenerate the README skills section from bundles.yaml and "
            "sync release-tag pins to pyproject.toml"
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if README.md is out of date",
    )
    args = parser.parse_args()

    repo_root = _repo_root()
    readme_path = repo_root / "README.md"
    rendered = render_readme(repo_root=repo_root)

    if args.check:
        if readme_path.read_text(encoding="utf-8") != rendered:
            print(
                "README.md is out of date; "
                "run uv run python scripts/generate_readme.py",
                file=sys.stderr,
            )
            sys.exit(1)
        return

    readme_path.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
